### ISSUE TITLE
Add support for status of Slack channel members

### ISSUE THREAD

**Issue by huehnerlady** [hypoport/slack-wps-py#5]
The goal of this feature is to get the status of all the users in the _current_ channel.

the event handed into the handler includes the channel_id. With this channel_id you can use the slack API to get all the user_ids in that channel. After that you can use this ID to get the status.

**IMPORTANT:** The user_ids are not supported yet, you have to code a workaround - or you have to wait until the user_ids are supported

**Comment by caspii** [comment]
Oh well. 😀
